apiVersion: v1
kind: Secret
metadata:
  name: workervotacaosecret
type: Opaque
data:
  ConnectionKafka: STRING DE CONEXÃO DO KAFKA EM BASE 64
  ConnectionSqlServer: STRING DE CONEXÃO DO SQL SERVER EM BASE 64